/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TakvimRouteImport } from './routes/takvim'
import { Route as SifreSifirlaRouteImport } from './routes/sifre-sifirla'
import { Route as KesfetRouteImport } from './routes/kesfet'
import { Route as IcgorulerRouteImport } from './routes/icgoruler'
import { Route as GunceRouteImport } from './routes/gunce'
import { Route as DonguRouteImport } from './routes/dongu'
import { Route as AyarlarRouteImport } from './routes/ayarlar'
import { Route as AraclarRouteImport } from './routes/araclar'
import { Route as AliskanliklarRouteImport } from './routes/aliskanliklar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AraclarIndexRouteImport } from './routes/araclar.index'
import { Route as AraclarYemekRouteImport } from './routes/araclar.yemek'
import { Route as AraclarTartiRouteImport } from './routes/araclar.tarti'
import { Route as AraclarProgramRouteImport } from './routes/araclar.program'
import { Route as AraclarNefesRouteImport } from './routes/araclar.nefes'
import { Route as AraclarHareketRouteImport } from './routes/araclar.hareket'
import { Route as AraclarGunlukRouteImport } from './routes/araclar.gunluk'

const TakvimRoute = TakvimRouteImport.update({
  id: '/takvim',
  path: '/takvim',
  getParentRoute: () => rootRouteImport,
} as any)
const SifreSifirlaRoute = SifreSifirlaRouteImport.update({
  id: '/sifre-sifirla',
  path: '/sifre-sifirla',
  getParentRoute: () => rootRouteImport,
} as any)
const KesfetRoute = KesfetRouteImport.update({
  id: '/kesfet',
  path: '/kesfet',
  getParentRoute: () => rootRouteImport,
} as any)
const IcgorulerRoute = IcgorulerRouteImport.update({
  id: '/icgoruler',
  path: '/icgoruler',
  getParentRoute: () => rootRouteImport,
} as any)
const GunceRoute = GunceRouteImport.update({
  id: '/gunce',
  path: '/gunce',
  getParentRoute: () => rootRouteImport,
} as any)
const DonguRoute = DonguRouteImport.update({
  id: '/dongu',
  path: '/dongu',
  getParentRoute: () => rootRouteImport,
} as any)
const AyarlarRoute = AyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const AraclarRoute = AraclarRouteImport.update({
  id: '/araclar',
  path: '/araclar',
  getParentRoute: () => rootRouteImport,
} as any)
const AliskanliklarRoute = AliskanliklarRouteImport.update({
  id: '/aliskanliklar',
  path: '/aliskanliklar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AraclarIndexRoute = AraclarIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AraclarRoute,
} as any)
const AraclarYemekRoute = AraclarYemekRouteImport.update({
  id: '/yemek',
  path: '/yemek',
  getParentRoute: () => AraclarRoute,
} as any)
const AraclarTartiRoute = AraclarTartiRouteImport.update({
  id: '/tarti',
  path: '/tarti',
  getParentRoute: () => AraclarRoute,
} as any)
const AraclarProgramRoute = AraclarProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => AraclarRoute,
} as any)
const AraclarNefesRoute = AraclarNefesRouteImport.update({
  id: '/nefes',
  path: '/nefes',
  getParentRoute: () => AraclarRoute,
} as any)
const AraclarHareketRoute = AraclarHareketRouteImport.update({
  id: '/hareket',
  path: '/hareket',
  getParentRoute: () => AraclarRoute,
} as any)
const AraclarGunlukRoute = AraclarGunlukRouteImport.update({
  id: '/gunluk',
  path: '/gunluk',
  getParentRoute: () => AraclarRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aliskanliklar': typeof AliskanliklarRoute
  '/araclar': typeof AraclarRouteWithChildren
  '/ayarlar': typeof AyarlarRoute
  '/dongu': typeof DonguRoute
  '/gunce': typeof GunceRoute
  '/icgoruler': typeof IcgorulerRoute
  '/kesfet': typeof KesfetRoute
  '/sifre-sifirla': typeof SifreSifirlaRoute
  '/takvim': typeof TakvimRoute
  '/araclar/gunluk': typeof AraclarGunlukRoute
  '/araclar/hareket': typeof AraclarHareketRoute
  '/araclar/nefes': typeof AraclarNefesRoute
  '/araclar/program': typeof AraclarProgramRoute
  '/araclar/tarti': typeof AraclarTartiRoute
  '/araclar/yemek': typeof AraclarYemekRoute
  '/araclar/': typeof AraclarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aliskanliklar': typeof AliskanliklarRoute
  '/ayarlar': typeof AyarlarRoute
  '/dongu': typeof DonguRoute
  '/gunce': typeof GunceRoute
  '/icgoruler': typeof IcgorulerRoute
  '/kesfet': typeof KesfetRoute
  '/sifre-sifirla': typeof SifreSifirlaRoute
  '/takvim': typeof TakvimRoute
  '/araclar/gunluk': typeof AraclarGunlukRoute
  '/araclar/hareket': typeof AraclarHareketRoute
  '/araclar/nefes': typeof AraclarNefesRoute
  '/araclar/program': typeof AraclarProgramRoute
  '/araclar/tarti': typeof AraclarTartiRoute
  '/araclar/yemek': typeof AraclarYemekRoute
  '/araclar': typeof AraclarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aliskanliklar': typeof AliskanliklarRoute
  '/araclar': typeof AraclarRouteWithChildren
  '/ayarlar': typeof AyarlarRoute
  '/dongu': typeof DonguRoute
  '/gunce': typeof GunceRoute
  '/icgoruler': typeof IcgorulerRoute
  '/kesfet': typeof KesfetRoute
  '/sifre-sifirla': typeof SifreSifirlaRoute
  '/takvim': typeof TakvimRoute
  '/araclar/gunluk': typeof AraclarGunlukRoute
  '/araclar/hareket': typeof AraclarHareketRoute
  '/araclar/nefes': typeof AraclarNefesRoute
  '/araclar/program': typeof AraclarProgramRoute
  '/araclar/tarti': typeof AraclarTartiRoute
  '/araclar/yemek': typeof AraclarYemekRoute
  '/araclar/': typeof AraclarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aliskanliklar'
    | '/araclar'
    | '/ayarlar'
    | '/dongu'
    | '/gunce'
    | '/icgoruler'
    | '/kesfet'
    | '/sifre-sifirla'
    | '/takvim'
    | '/araclar/gunluk'
    | '/araclar/hareket'
    | '/araclar/nefes'
    | '/araclar/program'
    | '/araclar/tarti'
    | '/araclar/yemek'
    | '/araclar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aliskanliklar'
    | '/ayarlar'
    | '/dongu'
    | '/gunce'
    | '/icgoruler'
    | '/kesfet'
    | '/sifre-sifirla'
    | '/takvim'
    | '/araclar/gunluk'
    | '/araclar/hareket'
    | '/araclar/nefes'
    | '/araclar/program'
    | '/araclar/tarti'
    | '/araclar/yemek'
    | '/araclar'
  id:
    | '__root__'
    | '/'
    | '/aliskanliklar'
    | '/araclar'
    | '/ayarlar'
    | '/dongu'
    | '/gunce'
    | '/icgoruler'
    | '/kesfet'
    | '/sifre-sifirla'
    | '/takvim'
    | '/araclar/gunluk'
    | '/araclar/hareket'
    | '/araclar/nefes'
    | '/araclar/program'
    | '/araclar/tarti'
    | '/araclar/yemek'
    | '/araclar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AliskanliklarRoute: typeof AliskanliklarRoute
  AraclarRoute: typeof AraclarRouteWithChildren
  AyarlarRoute: typeof AyarlarRoute
  DonguRoute: typeof DonguRoute
  GunceRoute: typeof GunceRoute
  IcgorulerRoute: typeof IcgorulerRoute
  KesfetRoute: typeof KesfetRoute
  SifreSifirlaRoute: typeof SifreSifirlaRoute
  TakvimRoute: typeof TakvimRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/takvim': {
      id: '/takvim'
      path: '/takvim'
      fullPath: '/takvim'
      preLoaderRoute: typeof TakvimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sifre-sifirla': {
      id: '/sifre-sifirla'
      path: '/sifre-sifirla'
      fullPath: '/sifre-sifirla'
      preLoaderRoute: typeof SifreSifirlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kesfet': {
      id: '/kesfet'
      path: '/kesfet'
      fullPath: '/kesfet'
      preLoaderRoute: typeof KesfetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/icgoruler': {
      id: '/icgoruler'
      path: '/icgoruler'
      fullPath: '/icgoruler'
      preLoaderRoute: typeof IcgorulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gunce': {
      id: '/gunce'
      path: '/gunce'
      fullPath: '/gunce'
      preLoaderRoute: typeof GunceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dongu': {
      id: '/dongu'
      path: '/dongu'
      fullPath: '/dongu'
      preLoaderRoute: typeof DonguRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayarlar': {
      id: '/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/araclar': {
      id: '/araclar'
      path: '/araclar'
      fullPath: '/araclar'
      preLoaderRoute: typeof AraclarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aliskanliklar': {
      id: '/aliskanliklar'
      path: '/aliskanliklar'
      fullPath: '/aliskanliklar'
      preLoaderRoute: typeof AliskanliklarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/araclar/': {
      id: '/araclar/'
      path: '/'
      fullPath: '/araclar/'
      preLoaderRoute: typeof AraclarIndexRouteImport
      parentRoute: typeof AraclarRoute
    }
    '/araclar/yemek': {
      id: '/araclar/yemek'
      path: '/yemek'
      fullPath: '/araclar/yemek'
      preLoaderRoute: typeof AraclarYemekRouteImport
      parentRoute: typeof AraclarRoute
    }
    '/araclar/tarti': {
      id: '/araclar/tarti'
      path: '/tarti'
      fullPath: '/araclar/tarti'
      preLoaderRoute: typeof AraclarTartiRouteImport
      parentRoute: typeof AraclarRoute
    }
    '/araclar/program': {
      id: '/araclar/program'
      path: '/program'
      fullPath: '/araclar/program'
      preLoaderRoute: typeof AraclarProgramRouteImport
      parentRoute: typeof AraclarRoute
    }
    '/araclar/nefes': {
      id: '/araclar/nefes'
      path: '/nefes'
      fullPath: '/araclar/nefes'
      preLoaderRoute: typeof AraclarNefesRouteImport
      parentRoute: typeof AraclarRoute
    }
    '/araclar/hareket': {
      id: '/araclar/hareket'
      path: '/hareket'
      fullPath: '/araclar/hareket'
      preLoaderRoute: typeof AraclarHareketRouteImport
      parentRoute: typeof AraclarRoute
    }
    '/araclar/gunluk': {
      id: '/araclar/gunluk'
      path: '/gunluk'
      fullPath: '/araclar/gunluk'
      preLoaderRoute: typeof AraclarGunlukRouteImport
      parentRoute: typeof AraclarRoute
    }
  }
}

interface AraclarRouteChildren {
  AraclarGunlukRoute: typeof AraclarGunlukRoute
  AraclarHareketRoute: typeof AraclarHareketRoute
  AraclarNefesRoute: typeof AraclarNefesRoute
  AraclarProgramRoute: typeof AraclarProgramRoute
  AraclarTartiRoute: typeof AraclarTartiRoute
  AraclarYemekRoute: typeof AraclarYemekRoute
  AraclarIndexRoute: typeof AraclarIndexRoute
}

const AraclarRouteChildren: AraclarRouteChildren = {
  AraclarGunlukRoute: AraclarGunlukRoute,
  AraclarHareketRoute: AraclarHareketRoute,
  AraclarNefesRoute: AraclarNefesRoute,
  AraclarProgramRoute: AraclarProgramRoute,
  AraclarTartiRoute: AraclarTartiRoute,
  AraclarYemekRoute: AraclarYemekRoute,
  AraclarIndexRoute: AraclarIndexRoute,
}

const AraclarRouteWithChildren =
  AraclarRoute._addFileChildren(AraclarRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AliskanliklarRoute: AliskanliklarRoute,
  AraclarRoute: AraclarRouteWithChildren,
  AyarlarRoute: AyarlarRoute,
  DonguRoute: DonguRoute,
  GunceRoute: GunceRoute,
  IcgorulerRoute: IcgorulerRoute,
  KesfetRoute: KesfetRoute,
  SifreSifirlaRoute: SifreSifirlaRoute,
  TakvimRoute: TakvimRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
